/**
 * curator.io client
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.mallorcasoftware.curatorioclient.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * FeedPost
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-05T02:02:56.822+02:00")
public class FeedPost   {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("network_id")
  private Integer networkId = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("flagged")
  private Integer flagged = null;

  @SerializedName("has_media")
  private Integer hasMedia = null;

  @SerializedName("source_type")
  private Integer sourceType = null;

  @SerializedName("source_identifier")
  private String sourceIdentifier = null;

  @SerializedName("source_created_at")
  private DateTime sourceCreatedAt = null;

  @SerializedName("user_screen_name")
  private String userScreenName = null;

  @SerializedName("user_full_name")
  private String userFullName = null;

  @SerializedName("user_image")
  private String userImage = null;

  @SerializedName("text")
  private String text = null;

  @SerializedName("image")
  private String image = null;

  @SerializedName("image_large")
  private String imageLarge = null;

  @SerializedName("video")
  private String video = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("userUrl")
  private String userUrl = null;

  @SerializedName("thumbnail")
  private String thumbnail = null;

  @SerializedName("video_width")
  private Integer videoWidth = null;

  @SerializedName("video_height")
  private Integer videoHeight = null;

  @SerializedName("network_name")
  private String networkName = null;

  @SerializedName("comments")
  private Integer comments = null;

  @SerializedName("views")
  private Integer views = null;

  @SerializedName("likes")
  private Integer likes = null;

  @SerializedName("longitude")
  private Float longitude = null;

  @SerializedName("latitude")
  private Float latitude = null;

  @SerializedName("location_name")
  private String locationName = null;

  @SerializedName("image_width")
  private Integer imageWidth = null;

  @SerializedName("image_height")
  private Integer imageHeight = null;

  @SerializedName("has_image")
  private Integer hasImage = null;

  @SerializedName("has_video")
  private Integer hasVideo = null;

  public FeedPost id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public FeedPost networkId(Integer networkId) {
    this.networkId = networkId;
    return this;
  }

   /**
   * Get networkId
   * @return networkId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getNetworkId() {
    return networkId;
  }

  public void setNetworkId(Integer networkId) {
    this.networkId = networkId;
  }

  public FeedPost status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public FeedPost flagged(Integer flagged) {
    this.flagged = flagged;
    return this;
  }

   /**
   * Get flagged
   * @return flagged
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getFlagged() {
    return flagged;
  }

  public void setFlagged(Integer flagged) {
    this.flagged = flagged;
  }

  public FeedPost hasMedia(Integer hasMedia) {
    this.hasMedia = hasMedia;
    return this;
  }

   /**
   * Get hasMedia
   * @return hasMedia
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getHasMedia() {
    return hasMedia;
  }

  public void setHasMedia(Integer hasMedia) {
    this.hasMedia = hasMedia;
  }

  public FeedPost sourceType(Integer sourceType) {
    this.sourceType = sourceType;
    return this;
  }

   /**
   * Get sourceType
   * @return sourceType
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSourceType() {
    return sourceType;
  }

  public void setSourceType(Integer sourceType) {
    this.sourceType = sourceType;
  }

  public FeedPost sourceIdentifier(String sourceIdentifier) {
    this.sourceIdentifier = sourceIdentifier;
    return this;
  }

   /**
   * Get sourceIdentifier
   * @return sourceIdentifier
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSourceIdentifier() {
    return sourceIdentifier;
  }

  public void setSourceIdentifier(String sourceIdentifier) {
    this.sourceIdentifier = sourceIdentifier;
  }

  public FeedPost sourceCreatedAt(DateTime sourceCreatedAt) {
    this.sourceCreatedAt = sourceCreatedAt;
    return this;
  }

   /**
   * Get sourceCreatedAt
   * @return sourceCreatedAt
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getSourceCreatedAt() {
    return sourceCreatedAt;
  }

  public void setSourceCreatedAt(DateTime sourceCreatedAt) {
    this.sourceCreatedAt = sourceCreatedAt;
  }

  public FeedPost userScreenName(String userScreenName) {
    this.userScreenName = userScreenName;
    return this;
  }

   /**
   * Get userScreenName
   * @return userScreenName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserScreenName() {
    return userScreenName;
  }

  public void setUserScreenName(String userScreenName) {
    this.userScreenName = userScreenName;
  }

  public FeedPost userFullName(String userFullName) {
    this.userFullName = userFullName;
    return this;
  }

   /**
   * Get userFullName
   * @return userFullName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserFullName() {
    return userFullName;
  }

  public void setUserFullName(String userFullName) {
    this.userFullName = userFullName;
  }

  public FeedPost userImage(String userImage) {
    this.userImage = userImage;
    return this;
  }

   /**
   * Get userImage
   * @return userImage
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserImage() {
    return userImage;
  }

  public void setUserImage(String userImage) {
    this.userImage = userImage;
  }

  public FeedPost text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public FeedPost image(String image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public FeedPost imageLarge(String imageLarge) {
    this.imageLarge = imageLarge;
    return this;
  }

   /**
   * Get imageLarge
   * @return imageLarge
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getImageLarge() {
    return imageLarge;
  }

  public void setImageLarge(String imageLarge) {
    this.imageLarge = imageLarge;
  }

  public FeedPost video(String video) {
    this.video = video;
    return this;
  }

   /**
   * Get video
   * @return video
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVideo() {
    return video;
  }

  public void setVideo(String video) {
    this.video = video;
  }

  public FeedPost url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public FeedPost userUrl(String userUrl) {
    this.userUrl = userUrl;
    return this;
  }

   /**
   * Get userUrl
   * @return userUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserUrl() {
    return userUrl;
  }

  public void setUserUrl(String userUrl) {
    this.userUrl = userUrl;
  }

  public FeedPost thumbnail(String thumbnail) {
    this.thumbnail = thumbnail;
    return this;
  }

   /**
   * Get thumbnail
   * @return thumbnail
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getThumbnail() {
    return thumbnail;
  }

  public void setThumbnail(String thumbnail) {
    this.thumbnail = thumbnail;
  }

  public FeedPost videoWidth(Integer videoWidth) {
    this.videoWidth = videoWidth;
    return this;
  }

   /**
   * Get videoWidth
   * @return videoWidth
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getVideoWidth() {
    return videoWidth;
  }

  public void setVideoWidth(Integer videoWidth) {
    this.videoWidth = videoWidth;
  }

  public FeedPost videoHeight(Integer videoHeight) {
    this.videoHeight = videoHeight;
    return this;
  }

   /**
   * Get videoHeight
   * @return videoHeight
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getVideoHeight() {
    return videoHeight;
  }

  public void setVideoHeight(Integer videoHeight) {
    this.videoHeight = videoHeight;
  }

  public FeedPost networkName(String networkName) {
    this.networkName = networkName;
    return this;
  }

   /**
   * Get networkName
   * @return networkName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getNetworkName() {
    return networkName;
  }

  public void setNetworkName(String networkName) {
    this.networkName = networkName;
  }

  public FeedPost comments(Integer comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getComments() {
    return comments;
  }

  public void setComments(Integer comments) {
    this.comments = comments;
  }

  public FeedPost views(Integer views) {
    this.views = views;
    return this;
  }

   /**
   * Get views
   * @return views
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getViews() {
    return views;
  }

  public void setViews(Integer views) {
    this.views = views;
  }

  public FeedPost likes(Integer likes) {
    this.likes = likes;
    return this;
  }

   /**
   * Get likes
   * @return likes
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLikes() {
    return likes;
  }

  public void setLikes(Integer likes) {
    this.likes = likes;
  }

  public FeedPost longitude(Float longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getLongitude() {
    return longitude;
  }

  public void setLongitude(Float longitude) {
    this.longitude = longitude;
  }

  public FeedPost latitude(Float latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getLatitude() {
    return latitude;
  }

  public void setLatitude(Float latitude) {
    this.latitude = latitude;
  }

  public FeedPost locationName(String locationName) {
    this.locationName = locationName;
    return this;
  }

   /**
   * Get locationName
   * @return locationName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLocationName() {
    return locationName;
  }

  public void setLocationName(String locationName) {
    this.locationName = locationName;
  }

  public FeedPost imageWidth(Integer imageWidth) {
    this.imageWidth = imageWidth;
    return this;
  }

   /**
   * Get imageWidth
   * @return imageWidth
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getImageWidth() {
    return imageWidth;
  }

  public void setImageWidth(Integer imageWidth) {
    this.imageWidth = imageWidth;
  }

  public FeedPost imageHeight(Integer imageHeight) {
    this.imageHeight = imageHeight;
    return this;
  }

   /**
   * Get imageHeight
   * @return imageHeight
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getImageHeight() {
    return imageHeight;
  }

  public void setImageHeight(Integer imageHeight) {
    this.imageHeight = imageHeight;
  }

  public FeedPost hasImage(Integer hasImage) {
    this.hasImage = hasImage;
    return this;
  }

   /**
   * Get hasImage
   * @return hasImage
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getHasImage() {
    return hasImage;
  }

  public void setHasImage(Integer hasImage) {
    this.hasImage = hasImage;
  }

  public FeedPost hasVideo(Integer hasVideo) {
    this.hasVideo = hasVideo;
    return this;
  }

   /**
   * Get hasVideo
   * @return hasVideo
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getHasVideo() {
    return hasVideo;
  }

  public void setHasVideo(Integer hasVideo) {
    this.hasVideo = hasVideo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeedPost feedPost = (FeedPost) o;
    return Objects.equals(this.id, feedPost.id) &&
        Objects.equals(this.networkId, feedPost.networkId) &&
        Objects.equals(this.status, feedPost.status) &&
        Objects.equals(this.flagged, feedPost.flagged) &&
        Objects.equals(this.hasMedia, feedPost.hasMedia) &&
        Objects.equals(this.sourceType, feedPost.sourceType) &&
        Objects.equals(this.sourceIdentifier, feedPost.sourceIdentifier) &&
        Objects.equals(this.sourceCreatedAt, feedPost.sourceCreatedAt) &&
        Objects.equals(this.userScreenName, feedPost.userScreenName) &&
        Objects.equals(this.userFullName, feedPost.userFullName) &&
        Objects.equals(this.userImage, feedPost.userImage) &&
        Objects.equals(this.text, feedPost.text) &&
        Objects.equals(this.image, feedPost.image) &&
        Objects.equals(this.imageLarge, feedPost.imageLarge) &&
        Objects.equals(this.video, feedPost.video) &&
        Objects.equals(this.url, feedPost.url) &&
        Objects.equals(this.userUrl, feedPost.userUrl) &&
        Objects.equals(this.thumbnail, feedPost.thumbnail) &&
        Objects.equals(this.videoWidth, feedPost.videoWidth) &&
        Objects.equals(this.videoHeight, feedPost.videoHeight) &&
        Objects.equals(this.networkName, feedPost.networkName) &&
        Objects.equals(this.comments, feedPost.comments) &&
        Objects.equals(this.views, feedPost.views) &&
        Objects.equals(this.likes, feedPost.likes) &&
        Objects.equals(this.longitude, feedPost.longitude) &&
        Objects.equals(this.latitude, feedPost.latitude) &&
        Objects.equals(this.locationName, feedPost.locationName) &&
        Objects.equals(this.imageWidth, feedPost.imageWidth) &&
        Objects.equals(this.imageHeight, feedPost.imageHeight) &&
        Objects.equals(this.hasImage, feedPost.hasImage) &&
        Objects.equals(this.hasVideo, feedPost.hasVideo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, networkId, status, flagged, hasMedia, sourceType, sourceIdentifier, sourceCreatedAt, userScreenName, userFullName, userImage, text, image, imageLarge, video, url, userUrl, thumbnail, videoWidth, videoHeight, networkName, comments, views, likes, longitude, latitude, locationName, imageWidth, imageHeight, hasImage, hasVideo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeedPost {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    networkId: ").append(toIndentedString(networkId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    flagged: ").append(toIndentedString(flagged)).append("\n");
    sb.append("    hasMedia: ").append(toIndentedString(hasMedia)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    sourceIdentifier: ").append(toIndentedString(sourceIdentifier)).append("\n");
    sb.append("    sourceCreatedAt: ").append(toIndentedString(sourceCreatedAt)).append("\n");
    sb.append("    userScreenName: ").append(toIndentedString(userScreenName)).append("\n");
    sb.append("    userFullName: ").append(toIndentedString(userFullName)).append("\n");
    sb.append("    userImage: ").append(toIndentedString(userImage)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    imageLarge: ").append(toIndentedString(imageLarge)).append("\n");
    sb.append("    video: ").append(toIndentedString(video)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    userUrl: ").append(toIndentedString(userUrl)).append("\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    videoWidth: ").append(toIndentedString(videoWidth)).append("\n");
    sb.append("    videoHeight: ").append(toIndentedString(videoHeight)).append("\n");
    sb.append("    networkName: ").append(toIndentedString(networkName)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    views: ").append(toIndentedString(views)).append("\n");
    sb.append("    likes: ").append(toIndentedString(likes)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    locationName: ").append(toIndentedString(locationName)).append("\n");
    sb.append("    imageWidth: ").append(toIndentedString(imageWidth)).append("\n");
    sb.append("    imageHeight: ").append(toIndentedString(imageHeight)).append("\n");
    sb.append("    hasImage: ").append(toIndentedString(hasImage)).append("\n");
    sb.append("    hasVideo: ").append(toIndentedString(hasVideo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

